[package]
name = "spar-rust"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = [ "full" ] }
quote = "1.0"

rust-spp = { git = "https://github.com/GMAP/rust-ssp" }
